### ISSUE TITLE
unrelated to this repo - Julia meetup CPH (denmark)

### ISSUE THREAD

**Issue by mkborregaard** [EcoJulia/SpatialEcology.jl#17]
Jeg åbner et issue på mit eget repo for det er den nemmeste måde at tagge alle på.
I (@1oly @andreasnoack @cth @dhoegh @emilbayes @eugene @eveydee @kkholst @martinandersen @mkborregaard @pkofod @robertdj @simulkade @stemann @ulfworsoe) er alle danskere / folk der bor i DK der har github contributions til pakker i Julia's metadata. 

Vi prøver at starte et julia-meetup i Danmark. Der er et møde næste torsdag i København. Der er et event at tilmelde sig her: https://www.meetup.com/JuliaCPH/events/243862923/
Og i øvrigt en #danmark kanal på julia's slack :-)

Håber at se mange af jer!

**Comment by mkborregaard** [comment]
@bfredl, @mfalt og @rasmushenningsson er i Lund - det er jo lige over broen :-)

**Comment by emilbayes** [comment]
See you there 👋

**Comment by pkofod** [comment]
Hvis du ikke vil spamme SpatialEcology.jl så kan vi tage den på https://github.com/JuliaCPH/Meetups.jl

**Comment by mkborregaard** [comment]
God ide.

**Comment by mkborregaard** [comment]
sorry for the spam Tim.

**Comment by emilbayes** [comment]
Related issue: https://github.com/JuliaCPH/Meetups.jl/issues/1
