### ISSUE TITLE
WARNING: could not import Base.full into SpatialEcology

### ISSUE THREAD

**Issue by kescobo** [EcoJulia/SpatialEcology.jl#28]
This isn't causing me any problems, but it seems that `full` isn't in `Base` anymore. 

From [0.7 HISTORY](https://github.com/JuliaLang/julia/blob/master/HISTORY.md):

> full has been deprecated in favor of more specific, better defined alternatives. On structured matrices A, consider instead Matrix(A), Array(A), SparseMatrixCSC(A), or sparse(A). On sparse arrays S, consider instead Vector(S), Matrix(S), or Array(S) as appropriate. On factorizations F, consider instead Matrix(F), Array(F), AbstractMatrix(F), or AbstractArray(F). On implicit orthogonal factors Q, consider instead Matrix(Q) or Array(Q); for implicit orthogonal factors that can be recovered in square or truncated form, see the deprecation message for square recovery instructions. On Symmetric, Hermitian, or AbstractTriangular matrices A, consider instead Matrix(S), Array(S), SparseMatrixCSC(S), or sparse(S). On Symmetric matrices A particularly, consider instead LinAlg.copytri!(copy(parent(A)), A.uplo). On Hermitian matrices A particularly, consider instead LinAlg.copytri!(copy(parent(A)), A.uplo, true). On UpperTriangular matrices A particularly, consider instead triu!(copy(parent(A))). On LowerTriangular matrices A particularly, consider instead tril!(copy(parent(A))) (#24250).

Seems like an easy fix once it's decided what the best option is (the only culprits seems to be [here](https://github.com/EcoJulia/SpatialEcology.jl/blob/master/src/SpatialEcology.jl#L9) and [here](https://github.com/EcoJulia/SpatialEcology.jl/blob/master/src/Commatrix_functions.jl#L59)), but I didn't want to make a PR since I don't know which of the above options is suitable for this use.

**Comment by mkborregaard** [comment]
Thanks, it's already gone on my local branch

**Comment by mkborregaard** [comment]
I just tagged a version with some edits, including this. I'll push another one with more small fixes soon.
