### ISSUE TITLE
Missing release of 0.5.0?

### ISSUE THREAD

**Issue by claireh93** [EcoJulia/SpatialEcology.jl#31]
Hi @mkborregaard, 
We're trying to get our code working with the julia 1.0 release of SpatialEcology. When we look on GitHub, v0.5.0 seems to be released, but on julia we only have 0.4.3. Has something gone wrong?
Thanks!

**Comment by mkborregaard** [comment]
Yeah, the metadata maintainers forgot to merge the PR... https://github.com/JuliaLang/METADATA.jl/pull/18172
I've asked them to do it.

**Comment by mkborregaard** [comment]
Hi @claireh93 should be tagged now. Thanks for the reminder!
