### ISSUE TITLE
New release incorporating Distances?

### ISSUE THREAD

**Issue by kescobo** [EcoJulia/SpatialEcology.jl#38]
Looks like there hasn't been a release for almost a year - I'd love to get something that incorporates #36 at least so I can get off the master branch.

**Comment by mkborregaard** [comment]
Yes @kescobo I'll try to close the open issues and push a new release next week :pray:

**Comment by mkborregaard** [comment]
Registration PR tagged.
I didn't find time to close the issues - but I've got a new grant to work on ecology in Julia so I'm going to develop this much more actively this year.

**Comment by kescobo** [comment]
Great!
'
